require:
 - rubocop-rspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'syrphid.gemspec'
AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2.1
Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'specify']
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 10
Documentation:
  Enabled: false
