require:
 - rubocop-rspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - '*.gemspec'
AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2.1
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/_spec.rb'
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 15
Style/Documentation:
  Enabled: false
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
